
// Models



== 200_response [[model_200_response]]

Model for testing model name starting with number

[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *name* : `link:#model_integer[integer](int32)`



[unstyled]
* *class* : `link:#model_string[string]`




a|[source,json]
----
{
  "properties" : {
    "name" : {
      "type" : "integer",
      "format" : "int32"
    },
    "class" : {
      "type" : "string"
    }
  },
  "description" : "Model for testing model name starting with number",
  "xml" : {
    "name" : "Name"
  }
}
----

|===


== AdditionalPropertiesClass [[model_AdditionalPropertiesClass]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *map_property* : `map[string, link:#model_string[string]]`



[unstyled]
* *map_of_map_property* : `map[string, link:#model_map[map]]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "map_property" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "string"
      }
    },
    "map_of_map_property" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object",
        "additionalProperties" : {
          "type" : "string"
        }
      }
    }
  }
}
----

|===


== Animal [[model_Animal]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *className* : `link:#model_string[string]`


[none]
** [small]#_[red]##required##_#












[unstyled]
* *color* : `link:#model_string[string]`




a|[source,json]
----
{
  "required" : [ "className" ],
  "type" : "object",
  "properties" : {
    "className" : {
      "type" : "string"
    },
    "color" : {
      "type" : "string",
      "default" : "red"
    }
  },
  "discriminator" : {
    "propertyName" : "className"
  }
}
----

|===


== ApiResponse [[model_ApiResponse]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *code* : `link:#model_integer[integer](int32)`



[unstyled]
* *type* : `link:#model_string[string]`



[unstyled]
* *message* : `link:#model_string[string]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "code" : {
      "type" : "integer",
      "format" : "int32"
    },
    "type" : {
      "type" : "string"
    },
    "message" : {
      "type" : "string"
    }
  }
}
----

|===


== ArrayOfArrayOfNumberOnly [[model_ArrayOfArrayOfNumberOnly]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *ArrayArrayNumber* : `array[link:#model_array[array]]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "ArrayArrayNumber" : {
      "type" : "array",
      "items" : {
        "type" : "array",
        "items" : {
          "type" : "number"
        }
      }
    }
  }
}
----

|===


== ArrayOfNumberOnly [[model_ArrayOfNumberOnly]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *ArrayNumber* : `array[link:#model_number[number]]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "ArrayNumber" : {
      "type" : "array",
      "items" : {
        "type" : "number"
      }
    }
  }
}
----

|===


== ArrayTest [[model_ArrayTest]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *array_of_string* : `array[link:#model_string[string]]`



[unstyled]
* *array_array_of_integer* : `array[link:#model_array[array](int64)]`



[unstyled]
* *array_array_of_model* : `array[link:#model_array[array]]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "array_of_string" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "array_array_of_integer" : {
      "type" : "array",
      "items" : {
        "type" : "array",
        "items" : {
          "type" : "integer",
          "format" : "int64"
        }
      }
    },
    "array_array_of_model" : {
      "type" : "array",
      "items" : {
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/ReadOnlyFirst"
        }
      }
    }
  }
}
----

|===


== Capitalization [[model_Capitalization]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *smallCamel* : `link:#model_string[string]`



[unstyled]
* *CapitalCamel* : `link:#model_string[string]`



[unstyled]
* *small_Snake* : `link:#model_string[string]`



[unstyled]
* *Capital_Snake* : `link:#model_string[string]`



[unstyled]
* *SCA_ETH_Flow_Points* : `link:#model_string[string]`



[unstyled]
* *ATT_NAME* : `link:#model_string[string]`
* +Name of the pet +



a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "smallCamel" : {
      "type" : "string"
    },
    "CapitalCamel" : {
      "type" : "string"
    },
    "small_Snake" : {
      "type" : "string"
    },
    "Capital_Snake" : {
      "type" : "string"
    },
    "SCA_ETH_Flow_Points" : {
      "type" : "string"
    },
    "ATT_NAME" : {
      "type" : "string",
      "description" : "Name of the pet\n"
    }
  }
}
----

|===


== Cat [[model_Cat]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *className* : `link:#model_string[string]`


[none]
** [small]#_[red]##required##_#












[unstyled]
* *color* : `link:#model_string[string]`



[unstyled]
* *declawed* : `link:#model_boolean[boolean]`




a|[source,json]
----
{
  "allOf" : [ {
    "$ref" : "#/components/schemas/Animal"
  }, {
    "type" : "object",
    "properties" : {
      "declawed" : {
        "type" : "boolean"
      }
    }
  } ]
}
----

|===


== Category [[model_Category]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *id* : `link:#model_long[long](int64)`



[unstyled]
* *name* : `link:#model_string[string]`


[none]
** [small]#_[red]##required##_#













a|[source,json]
----
{
  "required" : [ "name" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64"
    },
    "name" : {
      "type" : "string",
      "default" : "default-name"
    }
  },
  "xml" : {
    "name" : "Category"
  }
}
----

|===


== ClassModel [[model_ClassModel]]

Model for testing model with "_class" property

[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *_class* : `link:#model_string[string]`




a|[source,json]
----
{
  "properties" : {
    "_class" : {
      "type" : "string"
    }
  },
  "description" : "Model for testing model with \"_class\" property"
}
----

|===


== Client [[model_Client]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *client* : `link:#model_string[string]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "client" : {
      "type" : "string"
    }
  }
}
----

|===


== Dog [[model_Dog]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *className* : `link:#model_string[string]`


[none]
** [small]#_[red]##required##_#












[unstyled]
* *color* : `link:#model_string[string]`



[unstyled]
* *breed* : `link:#model_string[string]`




a|[source,json]
----
{
  "allOf" : [ {
    "$ref" : "#/components/schemas/Animal"
  }, {
    "type" : "object",
    "properties" : {
      "breed" : {
        "type" : "string"
      }
    }
  } ]
}
----

|===


== EnumArrays [[model_EnumArrays]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *just_symbol* : `link:#model_string[string]`



[unstyled]
* *array_enum* : `array[link:#model_string[string]]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "just_symbol" : {
      "type" : "string",
      "enum" : [ ">=", "$" ]
    },
    "array_enum" : {
      "type" : "array",
      "items" : {
        "type" : "string",
        "enum" : [ "fish", "crab" ]
      }
    }
  }
}
----

|===


== EnumClass [[model_EnumClass]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|

a|[source,json]
----
{
  "type" : "string",
  "default" : "-efg",
  "enum" : [ "_abc", "-efg", "(xyz)" ]
}
----

|===


== Enum_Test [[model_Enum_Test]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *enum_string* : `link:#model_string[string]`



[unstyled]
* *enum_string_required* : `link:#model_string[string]`


[none]
** [small]#_[red]##required##_#












[unstyled]
* *enum_integer* : `link:#model_integer[integer](int32)`



[unstyled]
* *enum_number* : `link:#model_double[double](double)`



[unstyled]
* *outerEnum* : `link:#model_OuterEnum[OuterEnum]`



[unstyled]
* *outerEnumInteger* : `link:#model_OuterEnumInteger[OuterEnumInteger]`



[unstyled]
* *outerEnumDefaultValue* : `link:#model_OuterEnumDefaultValue[OuterEnumDefaultValue]`



[unstyled]
* *outerEnumIntegerDefaultValue* : `link:#model_OuterEnumIntegerDefaultValue[OuterEnumIntegerDefaultValue]`




a|[source,json]
----
{
  "required" : [ "enum_string_required" ],
  "type" : "object",
  "properties" : {
    "enum_string" : {
      "type" : "string",
      "enum" : [ "UPPER", "lower", "" ]
    },
    "enum_string_required" : {
      "type" : "string",
      "enum" : [ "UPPER", "lower", "" ]
    },
    "enum_integer" : {
      "type" : "integer",
      "format" : "int32",
      "enum" : [ 1, -1 ]
    },
    "enum_number" : {
      "type" : "number",
      "format" : "double",
      "enum" : [ 1.1, -1.2 ]
    },
    "outerEnum" : {
      "$ref" : "#/components/schemas/OuterEnum"
    },
    "outerEnumInteger" : {
      "$ref" : "#/components/schemas/OuterEnumInteger"
    },
    "outerEnumDefaultValue" : {
      "$ref" : "#/components/schemas/OuterEnumDefaultValue"
    },
    "outerEnumIntegerDefaultValue" : {
      "$ref" : "#/components/schemas/OuterEnumIntegerDefaultValue"
    }
  }
}
----

|===


== File [[model_File]]

Must be named `File` for test.

[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *sourceURI* : `link:#model_string[string]`
* +Test capitalization+



a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "sourceURI" : {
      "type" : "string",
      "description" : "Test capitalization"
    }
  },
  "description" : "Must be named `File` for test."
}
----

|===


== FileSchemaTestClass [[model_FileSchemaTestClass]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *file* : `link:#model_File[File]`



[unstyled]
* *files* : `array[link:#model_File[File]]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "file" : {
      "$ref" : "#/components/schemas/File"
    },
    "files" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/File"
      }
    }
  }
}
----

|===


== Foo [[model_Foo]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *bar* : `link:#model_string[string]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "bar" : {
      "$ref" : "#/components/schemas/Bar"
    }
  }
}
----

|===


== format_test [[model_format_test]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *integer* : `link:#model_integer[integer]`


[none]



** [small]#_minimum:_ `10` (inclusive)#
** [small]#_maximum:_ `100` (inclusive)#








[unstyled]
* *int32* : `link:#model_integer[integer](int32)`


[none]



** [small]#_minimum:_ `20` (inclusive)#
** [small]#_maximum:_ `200` (inclusive)#








[unstyled]
* *int64* : `link:#model_long[long](int64)`



[unstyled]
* *number* : `link:#model_number[number]`


[none]
** [small]#_[red]##required##_#


** [small]#_minimum:_ `32.1` (inclusive)#
** [small]#_maximum:_ `543.2` (inclusive)#








[unstyled]
* *float* : `link:#model_float[float](float)`


[none]



** [small]#_minimum:_ `54.3` (inclusive)#
** [small]#_maximum:_ `987.6` (inclusive)#








[unstyled]
* *double* : `link:#model_double[double](double)`


[none]



** [small]#_minimum:_ `67.8` (inclusive)#
** [small]#_maximum:_ `123.4` (inclusive)#








[unstyled]
* *string* : `link:#model_string[string]`


[none]









** [small]#_pattern:_ `/[a-z]/i`#



[unstyled]
* *byte* : `link:#model_ByteArray[ByteArray](byte)`


[none]
** [small]#_[red]##required##_#












[unstyled]
* *binary* : `link:#model_file[file](binary)`



[unstyled]
* *date* : `link:#model_date[date](date)`


[none]
** [small]#_[red]##required##_#












[unstyled]
* *dateTime* : `link:#model_DateTime[DateTime](date-time)`



[unstyled]
* *uuid* : `link:#model_UUID[UUID](uuid)`

* _Ex:_ `+72f98069-206d-4f12-9f12-3d1e525a8e84+`

[unstyled]
* *password* : `link:#model_string[string](password)`


[none]
** [small]#_[red]##required##_#




** [small]#_minLength:_ `10`#
** [small]#_maxLength:_ `64`#






[unstyled]
* *pattern_with_digits* : `link:#model_string[string]`
* +A string that is a 10 digit number. Can have leading zeros.+

[none]









** [small]#_pattern:_ `/^\\d{10}$/`#



[unstyled]
* *pattern_with_digits_and_delimiter* : `link:#model_string[string]`
* +A string starting with &#39;image_&#39; (case insensitive) and one to three digits following i.e. Image_01.+

[none]









** [small]#_pattern:_ `/^image_\\d{1,3}$/i`#




a|[source,json]
----
{
  "required" : [ "byte", "date", "number", "password" ],
  "type" : "object",
  "properties" : {
    "integer" : {
      "maximum" : 100,
      "minimum" : 10,
      "type" : "integer"
    },
    "int32" : {
      "maximum" : 200,
      "minimum" : 20,
      "type" : "integer",
      "format" : "int32"
    },
    "int64" : {
      "type" : "integer",
      "format" : "int64"
    },
    "number" : {
      "maximum" : 543.2,
      "minimum" : 32.1,
      "type" : "number"
    },
    "float" : {
      "maximum" : 987.6,
      "minimum" : 54.3,
      "type" : "number",
      "format" : "float"
    },
    "double" : {
      "maximum" : 123.4,
      "minimum" : 67.8,
      "type" : "number",
      "format" : "double"
    },
    "string" : {
      "pattern" : "/[a-z]/i",
      "type" : "string"
    },
    "byte" : {
      "type" : "string",
      "format" : "byte"
    },
    "binary" : {
      "type" : "string",
      "format" : "binary"
    },
    "date" : {
      "type" : "string",
      "format" : "date"
    },
    "dateTime" : {
      "type" : "string",
      "format" : "date-time"
    },
    "uuid" : {
      "type" : "string",
      "format" : "uuid",
      "example" : "72f98069-206d-4f12-9f12-3d1e525a8e84"
    },
    "password" : {
      "maxLength" : 64,
      "minLength" : 10,
      "type" : "string",
      "format" : "password"
    },
    "pattern_with_digits" : {
      "pattern" : "^\\d{10}$",
      "type" : "string",
      "description" : "A string that is a 10 digit number. Can have leading zeros."
    },
    "pattern_with_digits_and_delimiter" : {
      "pattern" : "/^image_\\d{1,3}$/i",
      "type" : "string",
      "description" : "A string starting with 'image_' (case insensitive) and one to three digits following i.e. Image_01."
    }
  }
}
----

|===


== hasOnlyReadOnly [[model_hasOnlyReadOnly]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *bar* : `link:#model_string[string]`



[unstyled]
* *foo* : `link:#model_string[string]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "bar" : {
      "type" : "string",
      "readOnly" : true
    },
    "foo" : {
      "type" : "string",
      "readOnly" : true
    }
  }
}
----

|===


== HealthCheckResult [[model_HealthCheckResult]]

Just a string to inform instance is up and running. Make it nullable in hope to get it as pointer in generated model.

[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *NullableMessage* : `link:#model_string[string]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "NullableMessage" : {
      "type" : "string",
      "nullable" : true
    }
  },
  "description" : "Just a string to inform instance is up and running. Make it nullable in hope to get it as pointer in generated model."
}
----

|===


== inline_object [[model_inline_object]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *name* : `link:#model_string[string]`
* +Updated name of the pet+


[unstyled]
* *status* : `link:#model_string[string]`
* +Updated status of the pet+



a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "name" : {
      "type" : "string",
      "description" : "Updated name of the pet"
    },
    "status" : {
      "type" : "string",
      "description" : "Updated status of the pet",
      "deprecated" : true
    }
  }
}
----

|===


== inline_object_1 [[model_inline_object_1]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *additionalMetadata* : `link:#model_string[string]`
* +Additional data to pass to server+


[unstyled]
* *file* : `link:#model_file[file](binary)`
* +file to upload+



a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "additionalMetadata" : {
      "type" : "string",
      "description" : "Additional data to pass to server"
    },
    "file" : {
      "type" : "string",
      "description" : "file to upload",
      "format" : "binary"
    }
  }
}
----

|===


== inline_object_2 [[model_inline_object_2]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *enum_form_string_array* : `array[link:#model_string[string]]`
* +Form parameter enum test (string array)+


[unstyled]
* *enum_form_string* : `link:#model_string[string]`
* +Form parameter enum test (string)+



a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "enum_form_string_array" : {
      "type" : "array",
      "description" : "Form parameter enum test (string array)",
      "items" : {
        "type" : "string",
        "default" : "$",
        "enum" : [ ">", "$" ]
      }
    },
    "enum_form_string" : {
      "type" : "string",
      "description" : "Form parameter enum test (string)",
      "default" : "-efg",
      "enum" : [ "_abc", "-efg", "(xyz)" ]
    }
  }
}
----

|===


== inline_object_3 [[model_inline_object_3]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *integer* : `link:#model_integer[integer]`
* +None+

[none]



** [small]#_minimum:_ `10` (inclusive)#
** [small]#_maximum:_ `100` (inclusive)#








[unstyled]
* *int32* : `link:#model_integer[integer](int32)`
* +None+

[none]



** [small]#_minimum:_ `20` (inclusive)#
** [small]#_maximum:_ `200` (inclusive)#








[unstyled]
* *int64* : `link:#model_long[long](int64)`
* +None+


[unstyled]
* *number* : `link:#model_number[number]`
* +None+

[none]
** [small]#_[red]##required##_#


** [small]#_minimum:_ `32.1` (inclusive)#
** [small]#_maximum:_ `543.2` (inclusive)#








[unstyled]
* *float* : `link:#model_float[float](float)`
* +None+

[none]




** [small]#_maximum:_ `987.6` (inclusive)#








[unstyled]
* *double* : `link:#model_double[double](double)`
* +None+

[none]
** [small]#_[red]##required##_#


** [small]#_minimum:_ `67.8` (inclusive)#
** [small]#_maximum:_ `123.4` (inclusive)#








[unstyled]
* *string* : `link:#model_string[string]`
* +None+

[none]









** [small]#_pattern:_ `/[a-z]/i`#



[unstyled]
* *pattern_without_delimiter* : `link:#model_string[string]`
* +None+

[none]
** [small]#_[red]##required##_#








** [small]#_pattern:_ `/^[A-Z].*/`#



[unstyled]
* *byte* : `link:#model_ByteArray[ByteArray](byte)`
* +None+

[none]
** [small]#_[red]##required##_#












[unstyled]
* *binary* : `link:#model_file[file](binary)`
* +None+


[unstyled]
* *date* : `link:#model_date[date](date)`
* +None+


[unstyled]
* *dateTime* : `link:#model_DateTime[DateTime](date-time)`
* +None+


[unstyled]
* *password* : `link:#model_string[string](password)`
* +None+

[none]





** [small]#_minLength:_ `10`#
** [small]#_maxLength:_ `64`#






[unstyled]
* *callback* : `link:#model_string[string]`
* +None+



a|[source,json]
----
{
  "required" : [ "byte", "double", "number", "pattern_without_delimiter" ],
  "type" : "object",
  "properties" : {
    "integer" : {
      "maximum" : 100,
      "minimum" : 10,
      "type" : "integer",
      "description" : "None"
    },
    "int32" : {
      "maximum" : 200,
      "minimum" : 20,
      "type" : "integer",
      "description" : "None",
      "format" : "int32"
    },
    "int64" : {
      "type" : "integer",
      "description" : "None",
      "format" : "int64"
    },
    "number" : {
      "maximum" : 543.2,
      "minimum" : 32.1,
      "type" : "number",
      "description" : "None"
    },
    "float" : {
      "maximum" : 987.6,
      "type" : "number",
      "description" : "None",
      "format" : "float"
    },
    "double" : {
      "maximum" : 123.4,
      "minimum" : 67.8,
      "type" : "number",
      "description" : "None",
      "format" : "double"
    },
    "string" : {
      "pattern" : "/[a-z]/i",
      "type" : "string",
      "description" : "None"
    },
    "pattern_without_delimiter" : {
      "pattern" : "^[A-Z].*",
      "type" : "string",
      "description" : "None"
    },
    "byte" : {
      "type" : "string",
      "description" : "None",
      "format" : "byte"
    },
    "binary" : {
      "type" : "string",
      "description" : "None",
      "format" : "binary"
    },
    "date" : {
      "type" : "string",
      "description" : "None",
      "format" : "date"
    },
    "dateTime" : {
      "type" : "string",
      "description" : "None",
      "format" : "date-time"
    },
    "password" : {
      "maxLength" : 64,
      "minLength" : 10,
      "type" : "string",
      "description" : "None",
      "format" : "password"
    },
    "callback" : {
      "type" : "string",
      "description" : "None"
    }
  }
}
----

|===


== inline_object_4 [[model_inline_object_4]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *param* : `link:#model_string[string]`
* +field1+

[none]
** [small]#_[red]##required##_#












[unstyled]
* *param2* : `link:#model_string[string]`
* +field2+

[none]
** [small]#_[red]##required##_#













a|[source,json]
----
{
  "required" : [ "param", "param2" ],
  "type" : "object",
  "properties" : {
    "param" : {
      "type" : "string",
      "description" : "field1"
    },
    "param2" : {
      "type" : "string",
      "description" : "field2"
    }
  }
}
----

|===


== inline_object_5 [[model_inline_object_5]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *additionalMetadata* : `link:#model_string[string]`
* +Additional data to pass to server+


[unstyled]
* *requiredFile* : `link:#model_file[file](binary)`
* +file to upload+

[none]
** [small]#_[red]##required##_#













a|[source,json]
----
{
  "required" : [ "requiredFile" ],
  "type" : "object",
  "properties" : {
    "additionalMetadata" : {
      "type" : "string",
      "description" : "Additional data to pass to server"
    },
    "requiredFile" : {
      "type" : "string",
      "description" : "file to upload",
      "format" : "binary"
    }
  }
}
----

|===


== inline_response_default [[model_inline_response_default]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *string* : `link:#model_Foo[Foo]`




a|[source,json]
----
{
  "properties" : {
    "string" : {
      "$ref" : "#/components/schemas/Foo"
    }
  }
}
----

|===


== List [[model_List]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *123-list* : `link:#model_string[string]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "123-list" : {
      "type" : "string"
    }
  }
}
----

|===


== MapTest [[model_MapTest]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *map_map_of_string* : `map[string, link:#model_map[map]]`



[unstyled]
* *map_of_enum_string* : `map[string, link:#model_string[string]]`



[unstyled]
* *direct_map* : `map[string, link:#model_boolean[boolean]]`



[unstyled]
* *indirect_map* : `map[string, link:#model_boolean[boolean]]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "map_map_of_string" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object",
        "additionalProperties" : {
          "type" : "string"
        }
      }
    },
    "map_of_enum_string" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "string",
        "enum" : [ "UPPER", "lower" ]
      }
    },
    "direct_map" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "boolean"
      }
    },
    "indirect_map" : {
      "$ref" : "#/components/schemas/StringBooleanMap"
    }
  }
}
----

|===


== MixedPropertiesAndAdditionalPropertiesClass [[model_MixedPropertiesAndAdditionalPropertiesClass]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *uuid* : `link:#model_UUID[UUID](uuid)`



[unstyled]
* *dateTime* : `link:#model_DateTime[DateTime](date-time)`



[unstyled]
* *map* : `map[string, link:#model_Animal[Animal]]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "uuid" : {
      "type" : "string",
      "format" : "uuid"
    },
    "dateTime" : {
      "type" : "string",
      "format" : "date-time"
    },
    "map" : {
      "type" : "object",
      "additionalProperties" : {
        "$ref" : "#/components/schemas/Animal"
      }
    }
  }
}
----

|===


== Name [[model_Name]]

Model for testing model name same as property name

[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *name* : `link:#model_integer[integer](int32)`


[none]
** [small]#_[red]##required##_#












[unstyled]
* *snake_case* : `link:#model_integer[integer](int32)`



[unstyled]
* *property* : `link:#model_string[string]`



[unstyled]
* *123Number* : `link:#model_integer[integer]`




a|[source,json]
----
{
  "required" : [ "name" ],
  "properties" : {
    "name" : {
      "type" : "integer",
      "format" : "int32"
    },
    "snake_case" : {
      "type" : "integer",
      "format" : "int32",
      "readOnly" : true
    },
    "property" : {
      "type" : "string"
    },
    "123Number" : {
      "type" : "integer",
      "readOnly" : true
    }
  },
  "description" : "Model for testing model name same as property name",
  "xml" : {
    "name" : "Name"
  }
}
----

|===


== NullableClass [[model_NullableClass]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *integer_prop* : `link:#model_integer[integer]`



[unstyled]
* *number_prop* : `link:#model_number[number]`



[unstyled]
* *boolean_prop* : `link:#model_boolean[boolean]`



[unstyled]
* *string_prop* : `link:#model_string[string]`



[unstyled]
* *date_prop* : `link:#model_date[date](date)`



[unstyled]
* *datetime_prop* : `link:#model_DateTime[DateTime](date-time)`



[unstyled]
* *array_nullable_prop* : `array[link:#model_object[object]]`



[unstyled]
* *array_and_items_nullable_prop* : `array[link:#model_object[object]]`



[unstyled]
* *array_items_nullable* : `array[link:#model_object[object]]`



[unstyled]
* *object_nullable_prop* : `map[string, link:#model_object[object]]`



[unstyled]
* *object_and_items_nullable_prop* : `map[string, link:#model_object[object]]`



[unstyled]
* *object_items_nullable* : `map[string, link:#model_object[object]]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "integer_prop" : {
      "type" : "integer",
      "nullable" : true
    },
    "number_prop" : {
      "type" : "number",
      "nullable" : true
    },
    "boolean_prop" : {
      "type" : "boolean",
      "nullable" : true
    },
    "string_prop" : {
      "type" : "string",
      "nullable" : true
    },
    "date_prop" : {
      "type" : "string",
      "format" : "date",
      "nullable" : true
    },
    "datetime_prop" : {
      "type" : "string",
      "format" : "date-time",
      "nullable" : true
    },
    "array_nullable_prop" : {
      "type" : "array",
      "nullable" : true,
      "items" : {
        "type" : "object"
      }
    },
    "array_and_items_nullable_prop" : {
      "type" : "array",
      "nullable" : true,
      "items" : {
        "type" : "object",
        "nullable" : true
      }
    },
    "array_items_nullable" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "nullable" : true
      }
    },
    "object_nullable_prop" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object"
      },
      "nullable" : true
    },
    "object_and_items_nullable_prop" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object",
        "nullable" : true
      },
      "nullable" : true
    },
    "object_items_nullable" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object",
        "nullable" : true
      }
    }
  },
  "additionalProperties" : {
    "type" : "object",
    "nullable" : true
  }
}
----

|===


== NumberOnly [[model_NumberOnly]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *JustNumber* : `link:#model_number[number]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "JustNumber" : {
      "type" : "number"
    }
  }
}
----

|===


== Order [[model_Order]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *id* : `link:#model_long[long](int64)`



[unstyled]
* *petId* : `link:#model_long[long](int64)`



[unstyled]
* *quantity* : `link:#model_integer[integer](int32)`



[unstyled]
* *shipDate* : `link:#model_DateTime[DateTime](date-time)`



[unstyled]
* *status* : `link:#model_string[string]`
* +Order Status+


[unstyled]
* *complete* : `link:#model_boolean[boolean]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64"
    },
    "petId" : {
      "type" : "integer",
      "format" : "int64"
    },
    "quantity" : {
      "type" : "integer",
      "format" : "int32"
    },
    "shipDate" : {
      "type" : "string",
      "format" : "date-time"
    },
    "status" : {
      "type" : "string",
      "description" : "Order Status",
      "enum" : [ "placed", "approved", "delivered" ]
    },
    "complete" : {
      "type" : "boolean",
      "default" : false
    }
  },
  "xml" : {
    "name" : "Order"
  }
}
----

|===


== OuterComposite [[model_OuterComposite]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *my_number* : `link:#model_number[number]`



[unstyled]
* *my_string* : `link:#model_string[string]`



[unstyled]
* *my_boolean* : `link:#model_boolean[boolean]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "my_number" : {
      "$ref" : "#/components/schemas/OuterNumber"
    },
    "my_string" : {
      "$ref" : "#/components/schemas/OuterString"
    },
    "my_boolean" : {
      "$ref" : "#/components/schemas/OuterBoolean"
    }
  }
}
----

|===


== OuterEnum [[model_OuterEnum]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|

a|[source,json]
----
{
  "type" : "string",
  "enum" : [ "placed", "approved", "delivered" ]
}
----

|===


== OuterEnumDefaultValue [[model_OuterEnumDefaultValue]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|

a|[source,json]
----
{
  "type" : "string",
  "default" : "placed",
  "enum" : [ "placed", "approved", "delivered" ]
}
----

|===


== OuterEnumInteger [[model_OuterEnumInteger]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|

a|[source,json]
----
{
  "type" : "integer",
  "enum" : [ 0, 1, 2 ]
}
----

|===


== OuterEnumIntegerDefaultValue [[model_OuterEnumIntegerDefaultValue]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|

a|[source,json]
----
{
  "type" : "integer",
  "default" : 0,
  "enum" : [ 0, 1, 2 ]
}
----

|===


== Pet [[model_Pet]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *id* : `link:#model_long[long](int64)`



[unstyled]
* *category* : `link:#model_Category[Category]`



[unstyled]
* *name* : `link:#model_string[string]`

* _Ex:_ `+doggie+`
[none]
** [small]#_[red]##required##_#












[unstyled]
* *photoUrls* : `array[link:#model_string[string]]`


[none]
** [small]#_[red]##required##_#












[unstyled]
* *tags* : `array[link:#model_Tag[Tag]]`



[unstyled]
* *status* : `link:#model_string[string]`
* +pet status in the store+



a|[source,json]
----
{
  "required" : [ "name", "photoUrls" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64",
      "x-is-unique" : true
    },
    "category" : {
      "$ref" : "#/components/schemas/Category"
    },
    "name" : {
      "type" : "string",
      "example" : "doggie"
    },
    "photoUrls" : {
      "type" : "array",
      "xml" : {
        "name" : "photoUrl",
        "wrapped" : true
      },
      "items" : {
        "type" : "string"
      }
    },
    "tags" : {
      "type" : "array",
      "xml" : {
        "name" : "tag",
        "wrapped" : true
      },
      "items" : {
        "$ref" : "#/components/schemas/Tag"
      }
    },
    "status" : {
      "type" : "string",
      "description" : "pet status in the store",
      "enum" : [ "available", "pending", "sold" ]
    }
  },
  "xml" : {
    "name" : "Pet"
  }
}
----

|===


== ReadOnlyFirst [[model_ReadOnlyFirst]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *bar* : `link:#model_string[string]`



[unstyled]
* *baz* : `link:#model_string[string]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "bar" : {
      "type" : "string",
      "readOnly" : true
    },
    "baz" : {
      "type" : "string"
    }
  }
}
----

|===


== Return [[model_Return]]

Model for testing reserved words

[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *return* : `link:#model_integer[integer](int32)`




a|[source,json]
----
{
  "properties" : {
    "return" : {
      "type" : "integer",
      "format" : "int32"
    }
  },
  "description" : "Model for testing reserved words",
  "xml" : {
    "name" : "Return"
  }
}
----

|===


== _special_model.name_ [[model__special_model.name_]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *$special[property.name]* : `link:#model_long[long](int64)`




a|[source,json]
----
{
  "properties" : {
    "$special[property.name]" : {
      "type" : "integer",
      "format" : "int64"
    }
  },
  "xml" : {
    "name" : "$special[model.name]"
  }
}
----

|===


== Tag [[model_Tag]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *id* : `link:#model_long[long](int64)`



[unstyled]
* *name* : `link:#model_string[string]`




a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64"
    },
    "name" : {
      "type" : "string"
    }
  },
  "xml" : {
    "name" : "Tag"
  },
  "x-no-doc" : null
}
----

|===


== User [[model_User]]



[cols="1m,1m",options="header"]
|===
|Properties|Schema
a|
[unstyled]
* *id* : `link:#model_long[long](int64)`



[unstyled]
* *username* : `link:#model_string[string]`
* +Users username+
* _Ex:_ `+bartTheMan+`

[unstyled]
* *firstName* : `link:#model_string[string]`
* +hello: code: &#x60;public void setX&#x60; .bullets * one * two * three +


[unstyled]
* *lastName* : `link:#model_string[string]`



[unstyled]
* *email* : `link:#model_string[string]`



[unstyled]
* *password* : `link:#model_string[string]`



[unstyled]
* *phone* : `link:#model_string[string]`



[unstyled]
* *userStatus* : `link:#model_integer[integer](int32)`
* +User Status+



a|[source,json]
----
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64",
      "x-is-unique" : true
    },
    "username" : {
      "type" : "string",
      "description" : "Users username",
      "example" : "bartTheMan"
    },
    "firstName" : {
      "type" : "string",
      "description" : "hello:\ncode: `public void setX`\n.bullets * one * two * three "
    },
    "lastName" : {
      "type" : "string"
    },
    "email" : {
      "type" : "string"
    },
    "password" : {
      "type" : "string"
    },
    "phone" : {
      "type" : "string"
    },
    "userStatus" : {
      "type" : "integer",
      "description" : "User Status",
      "format" : "int32"
    }
  },
  "xml" : {
    "name" : "User"
  }
}
----

|===

